import ServicesComponent from './ServicesComponent';
import image7 from '../../assets/images/image-7.jpg';
import image12 from '../../assets/images/image-12.jpg';
import image13 from '../../assets/images/image-13.jpg';
import image14 from '../../assets/images/image-14.jpg';
import image15 from '../../assets/images/image-15.jpg';
import image17 from '../../assets/images/image-17.jpg';
import image18 from '../../assets/images/image-18.jpg';
import image19 from '../../assets/images/image-19.jpg';
import image20 from '../../assets/images/image-20.jpg';
import image21 from '../../assets/images/image-21.jpg';
import image22 from '../../assets/images/image-22.jpg';

export default function ServicesSection(){
  const services = [
    {title: 'Engine Repair', description: 'Heavy duty truck engine repair service is essential to keeping your truck engine in top condition. At the auto shop, our highly trained technicians specialize in heavy-duty truck engine repair and maintenance, ensuring your truck runs efficiently and reliably. Includes a complete diagnosis, component repair, preventive maintenance and necessary adjustments.', reasons: [{title: 'Optimal performance: ', description: ' Ensures efficiency and meeting deadlines.'}, {title: 'Cost savings: ', description: ' Prevents major and costly damages.'}, {title: 'Safety: ', description: ' Reduces the risk of mechanical failures.'}, {title: 'Longevity: ', description: ' Extends the vehicle’s lifespan.'}, {title: 'Regulatory compliance: ', description: ' Helps meet environmental standards.'}], paragraph: 'Trust us to keep your engine running perfectly, ensuring your truck is always ready for the road.'},

    {title: 'Brake Replacement', description: 'Our Brake Replacement service is essential for the safety and performance of your heavy duty truck. It includes a thorough inspection, replacement of brake components, and necessary adjustments. We use high-quality parts and advanced tools to ensure your braking system is reliable and efficient.', reasons: [{title: 'Enhanced safety: ', description: ' Ensures reliable braking and reduces accident risk.'}, {title: 'Improved performance: ', description: ' Maintains vehicle control and stopping power.'}, {title: 'Avoids downtime: ', description: ' Prevents unexpected brake failures and costly repairs.'}, {title: 'Prolongs lifespan: ', description: ' Extends the life of your braking system and other components.'}, {title: 'Compliance: ', description: ' Meets safety regulations and standards.'}], paragraph: 'Let us handle your brake replacement needs, providing top-notch service to keep your truck safe and dependable on the road.'},

    {title: 'Aluminum Welding', description: 'Our Aluminum Welding service is essential for maintaining the integrity and safety of your commercial trailers. It includes repairing floors and internal parts by welding to patch damaged areas.', reasons: [{title: 'Enhanced durability: ', description: ' Strengthens and repairs damaged areas.'}, {title: 'Improved safety: ', description: ' Ensures structural integrity and reduces accident risk.'}, {title: 'Cost-effective: ', description: ' Prevents further damage and costly replacements.'}, {title: 'Compliance: ', description: ' Meets industry safety standards.'}, {title: 'Aesthetic improvement: ', description: ' Restores appearance and functionality.'}], paragraph: 'Trust us to handle your aluminum welding needs, ensuring your commercial trailers stay safe, reliable, and in top condition.'},

    {title: 'Trailer Axle Repair', description: 'Our Trailer Axle Repair service is essential for maintaining the safety and performance of your commercial trailers. It includes thorough inspections, repairs, and adjustments of axle components to ensure optimal functionality.', reasons: [{title: 'Safety assurance: ', description: ' Guarantees reliable and secure trailer operation on the road.'}, {title: 'Optimized performance: ', description: ' Preserves proper alignment and weight distribution for efficient hauling.'}, {title: 'Cost-effective maintenance: ', description: ' Prevents major breakdowns and costly replacements down the line.'}, {title: 'Extended trailer lifespan: ', description: " Promotes durability and resilience, prolonging the trailer's overall usability."}, {title: 'Regulatory compliance: ', description: ' Meets stringent industry standards, ensuring legal and safe operation.'}], paragraph: 'Count on us to address your trailer axle repair needs with expertise, ensuring your commercial trailers remain safe, reliable, and ready for the journey ahead.'},

    {title: 'Oil Change', description: 'Our Oil Change Service is vital for maintaining the health and performance of your heavy duty truck. It includes draining old oil, replacing the oil filter, and refilling with high-quality oil suitable for your engine.', reasons: [{title: 'Enhanced engine performance: ', description: ' Keeps your engine running smoothly and efficiently.'}, {title: 'Prevents damage: ', description: ' Reduces engine wear and prevents sludge buildup.'}, {title: 'Cost-effective maintenance: ', description: ' Extends the life of your engine, avoiding costly repairs.'}, {title: 'Improved fuel efficiency: ', description: " Ensures optimal fuel consumption."}, {title: 'Regulatory compliance: ', description: ' Meets manufacturer specifications and industry standards.'}], paragraph: 'Trust us to provide timely and professional oil changes, ensuring your heavy duty truck stays in peak condition and ready for the road.'},

    {title: 'Trailer Repair', description: 'Our Trailer Repair service is vital for ensuring the reliability and longevity of your commercial trailers. From minor fixes to major overhauls, our comprehensive approach covers all aspects of trailer maintenance and repair.', reasons: [{title: 'Enhanced safety: ', description: ' Ensures all parts of the trailer are functioning correctly, reducing accident risk.'}, {title: 'Optimal performance: ', description: ' Keeps your trailer in top condition for efficient transport.'}, {title: 'Cost-effective maintenance: ', description: ' Prevents major issues and costly breakdowns.'}, {title: 'Extended lifespan: ', description: " Increases the durability and longevity of your trailer."}, {title: 'Regulatory compliance: ', description: ' Meets industry standards and safety regulations.'}], paragraph: 'Rely on us to provide expert trailer repair services, keeping your commercial trailers in peak condition and ready to tackle any journey.'},

    {title: 'Truck Tires', description: 'Our Truck Tires Service is essential for the safety and performance of your heavy duty trucks. It includes tire inspections, rotations, balancing, and replacements to ensure optimal traction and durability.', reasons: [{title: 'Safety assurance: ', description: ' Provides reliable traction and handling, minimizing accident risks.'}, {title: 'Enhanced efficiency: ', description: ' Maintains correct tire pressure and alignment for smooth driving and optimal fuel efficiency.'}, {title: 'Cost savings: ', description: ' Prevents uneven wear, extending tire life and reducing the need for frequent replacements.'}, {title: 'Prolonged tire life: ', description: " Boosts the durability and performance of your tires and vehicle."}, {title: 'Regulatory compliance: ', description: ' Adheres to industry standards and safety regulations for tires.'}], paragraph: 'Rely on us for comprehensive tire services, ensuring your heavy duty truck remains safe, efficient, and roadworthy.'},

    {title: 'Transmission Repair', description: 'Our Transmission Repair service is crucial for maintaining the smooth operation and longevity of your heavy duty truck. It includes detailed diagnostics, repairs, and replacements of transmission components to ensure optimal performance.', reasons: [{title: 'Smooth operation: ', description: ' Ensures seamless gear shifting and overall vehicle performance.'}, {title: 'Prevents breakdowns: ', description: ' Identifies and fixes issues early to avoid major transmission failures.'}, {title: 'Cost-effective: ', description: ' Addresses problems promptly, reducing the need for expensive repairs or replacements.'}, {title: 'Extended lifespan: ', description: " Enhances the durability and longevity of your transmission system."}, {title: 'Compliance: ', description: ' Meets manufacturer specifications and industry standards for transmission safety.'}], paragraph: 'Trust us to handle your transmission repair needs, ensuring your heavy duty truck stays reliable, efficient, and ready for the road.'},

    {title: 'Engine Rebuild', description: 'Our Engine Rebuild service is essential for restoring the performance and reliability of your heavy duty truck. It involves completely disassembling, cleaning, inspecting, and reassembling the engine with new or refurbished parts.', reasons: [{title: 'Restored power: ', description: ' Brings your engine back to its original performance, improving power and efficiency.'}, {title: 'Cost-effective alternative: ', description: ' More affordable than a complete engine replacement, providing a like-new engine.'}, {title: 'Preventative maintenance: ', description: ' Addresses all potential issues, preventing future breakdowns.'}, {title: 'Extended engine life: ', description: " Significantly prolongs the lifespan of your engine, ensuring long-term reliability."}, {title: 'Environmental benefits: ', description: ' Rebuilding an engine can be more environmentally friendly than manufacturing a new one.'}], paragraph: 'Rely on us for comprehensive engine rebuild services, ensuring your heavy duty truck runs like new and remains dependable for the long haul.'},

    {title: 'Computer Diagnostic and Forced Regeneration', description: 'Our Computer Diagnostic and Forced Regeneration service is essential for maintaining the performance and efficiency of your heavy duty truck. This service involves using advanced diagnostic tools to identify issues and performing forced regeneration to clean the diesel particulate filter (DPF).', reasons: [{title: 'Accurate diagnostics: ', description: ' Identifies and troubleshoots issues quickly using advanced computer technology.'}, {title: 'Enhanced performance: ', description: ' Ensures your engine runs efficiently by cleaning the DPF, reducing emissions and improving fuel economy.'}, {title: 'Preventative care: ', description: ' Detects problems early, preventing more severe and costly issues down the road.'}, {title: 'Regulatory compliance: ', description: " Helps your truck meet stringent emissions standards, avoiding fines and penalties."}, {title: 'Optimal uptime: ', description: ' Minimizes downtime by keeping your truck running smoothly and reliably.'}], paragraph: 'Trust us to provide expert computer diagnostic and forced regeneration services, ensuring your heavy duty truck remains efficient, compliant, and ready for the demands of the road.'},

    {title: 'A/C Diagnostic and Repair', description: "Our A/C Diagnostic and Repair service is crucial for maintaining the comfort and functionality of your heavy duty truck's air conditioning system. This service includes thorough diagnostics, leak detection, repairs, and recharging the system to ensure optimal performance.", reasons: [{title: 'Driver comfort: ', description: ' Ensures a comfortable cabin environment, especially during long hauls in hot weather.'}, {title: 'Efficient cooling: ', description: ' Identifies and fixes issues promptly to maintain efficient and reliable cooling.'}, {title: 'System longevity: ', description: ' Regular maintenance and timely repairs prevent more extensive damage to the A/C system.'}, {title: 'Improved air quality: ', description: " Ensures clean and cool air, contributing to a healthier driving experience."}, {title: 'Cost savings: ', description: ' Early detection and repair of issues can prevent expensive replacements and reduce overall maintenance costs.'}], paragraph: "Count on us for comprehensive A/C diagnostic and repair services, keeping your heavy duty truck's air conditioning system in top condition for a comfortable and efficient drive."}
  ]

  return (
    <>
      <ServicesComponent image={image12} description={services[0].description} id={'engine-repair'} title={services[0].title} reasons={services[0].reasons} paragraph={services[0].paragraph} />
      <ServicesComponent image={image13} rowReverse={true} description={services[1].description} title={services[1].title} reasons={services[1].reasons} paragraph={services[1].paragraph} backgroundColor={true} />
      <ServicesComponent image={image14} description={services[2].description} title={services[2].title} reasons={services[2].reasons} paragraph={services[2].paragraph} />
      <ServicesComponent image={image15} rowReverse={true} description={services[3].description} title={services[3].title} reasons={services[3].reasons} paragraph={services[3].paragraph} backgroundColor={true} />
      <ServicesComponent image={image7} description={services[4].description} title={services[4].title} reasons={services[4].reasons} paragraph={services[4].paragraph} id={'lube-oil-filters'} />
      <ServicesComponent image={image17} rowReverse={true} description={services[5].description} title={services[5].title} reasons={services[5].reasons} paragraph={services[5].paragraph} backgroundColor={true} />
      <ServicesComponent image={image18} description={services[6].description} title={services[6].title} reasons={services[6].reasons} paragraph={services[6].paragraph} />
      <ServicesComponent image={image19} rowReverse={true} description={services[7].description} title={services[7].title} reasons={services[7].reasons} paragraph={services[7].paragraph} backgroundColor={true} id={'transmission-repair'} />
      <ServicesComponent image={image20} description={services[8].description} title={services[8].title} reasons={services[8].reasons} paragraph={services[8].paragraph} />
      <ServicesComponent image={image21} rowReverse={true} description={services[9].description} title={services[9].title} reasons={services[9].reasons} paragraph={services[9].paragraph} backgroundColor={true} />
      <ServicesComponent image={image22} description={services[10].description} title={services[10].title} reasons={services[10].reasons} paragraph={services[10].paragraph} />
    </>
  )
}